spin_version = "1"
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple application that returns hello."
name = "spin-hello-world"
trigger = { type = "http", base = "/" }
version = "1.0.0"

[[component]]
id = "hello"
source = "target/wasm32-wasi/release/level1_hello_world.wasm"
description = "A simple component that returns hello."
[component.trigger]
route = "/hello"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
id = "level2"
source = "target/wasm32-wasi/release/level2.wasm"
environment = {SERVICE_URL = "https://some-random-api.ml/facts/bird"}
allowed_http_hosts = ["https://some-random-api.ml/"]
[component.trigger]
route = "/bird"
[component.build]
command = "cargo build --target wasm32-wasi --release"

[[component]]
environment = { REDIS_ADDRESS = "redis://127.0.0.1:6379", REDIS_CHANNEL = "messages" }
id = "level3"
source = "target/wasm32-wasi/release/rust_outbound_redis.wasm"
[component.trigger]
route = "/redis_publish"
channel = "messages"


